export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  SCHEDULE: "/schedule",
  SETTINGS: "/settings",
  ACCOUNTS: "/accounts",
  COURSES: "/courses",
  COURSE_DETAIL: (id: string) => `/courses/${id}`,
  ENROLLMENT: (courseId: string) => `/courses/${courseId}/enrollment`,
  ATTENDANCE: "/attendance",
  ASSIGNMENTS: "/assignments",
  GRADING: "/grading",
  NOTIFICATIONS: "/notifications",
  ACTIVITY: "/activity",
  ANALYTICS: "/analytics",
  STORAGE: "/storage",
  AI_ADVISOR: "/ai-advisor",

  /* Admin */
  ADMIN: "/admin",
  ADMIN_USER_MANAGEMENT: "/admin/users",
  ADMIN_COURSES: "/admin/courses",
  ADMIN_AI_INSIGHTS: "/admin/ai-insights",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_AUDIT_LOGS: "/admin/audit-logs",
} as const
